# Generated by Django 2.0.1 on 2018-01-20 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning', models.IntegerField(max_length=10)),
                ('pulls', models.IntegerField(default=0, max_length=6)),
                ('lettersfound', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
