# Generated by Django 2.0.1 on 2018-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0002_allfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfields',
            name='earning',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='allfields',
            name='lettersfound',
            field=models.CharField(default='', max_length=30),
        ),
    ]
