# Generated by Django 2.0.1 on 2018-01-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0003_auto_20180120_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfields',
            name='lettersfound',
            field=models.CharField(default='Null', max_length=30),
        ),
    ]
