# Generated by Django 2.0.1 on 2018-01-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0005_winners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winners',
            name='user',
        ),
        migrations.DeleteModel(
            name='Winners',
        ),
    ]
