# Generated by Django 2.0.1 on 2018-01-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0006_auto_20180120_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneypooled', models.IntegerField(default=0, max_length=10)),
            ],
        ),
    ]
